name: Deploy React app to S3 as static app

on:
  push:
    branches:
      - nonprod-ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
     AWS_REGION: us-east-2
     S3_BUCKET: partnerdev.unitedbydata.online.unitedway.org
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: NodeJs Setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build UI
        run: npm run build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws-region: ${{env.AWS_REGION}}
         
      - name: Deploy to S3
        #run: aws s3 sync build/ s3://${{env.S3_BUCKET}} --delete
        run: aws s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete
